name: Bug report
description: Report a reproducible bug
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What went wrong?
      placeholder: Briefly describe the bug.
    validations:
      required: true

  - type: dropdown
    id: module
    attributes:
      label: Affected module
      options:
        - mjml-java-core
        - mjml-java-resolvers
        - mjml-java-spring
        - mjml-java-bom
        - docs
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Minimal reproducible input and steps.
      placeholder: |
        MJML input:
        ...
        
        Steps:
        1. ...
        2. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior / errors
    validations:
      required: true

  - type: input
    id: java
    attributes:
      label: Java version
      placeholder: "e.g. 17.0.11"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: OS
      placeholder: "e.g. Ubuntu 22.04, macOS 14"
    validations:
      required: true
