name: Feature request
description: Suggest an improvement or new capability
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What user or developer problem does this solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the API/behavior you want.
    validations:
      required: true

  - type: dropdown
    id: module
    attributes:
      label: Target module
      options:
        - mjml-java-core
        - mjml-java-resolvers
        - mjml-java-spring
        - mjml-java-bom
        - docs
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workarounds or alternatives you've considered.
    validations:
      required: false
